### ISSUE TITLE
externalContentReviews Show blank page

### ISSUE THREAD

**Issue by hahuynhniteco** [advanced-cms/advanced-reviews#74]
I installed Advanced.CMS.AdvancedReviews - v 0.3.0 on EPiServer.CMS.Core - 11.12.0
and EPiServer.CMS.UI - 11.21.3

When add page to External review links with Edit, go to edit link and it shown blank page.
![externalContentReviews-show-blank-page](https://user-images.githubusercontent.com/44801946/65944216-6a6a0280-e45b-11e9-8b69-30a94a2ffbb9.png)
Thanks,
Ha

**Comment by barteksekula** [comment]
You must have a 404 from the underlaying iframe. Could you please share some more info? logs etc.?

**Comment by hahuynhniteco** [comment]
When open edit link externalContentReviews, login with account assigned to ExternalReviewers role. It shown the edit content page but it's blank. I have checked with iframe and the page is empty.
![externalContentReviews-show-blank-page](https://user-images.githubusercontent.com/44801946/65946390-3fce7880-e460-11e9-8b63-dcdfa1bd5f50.png)
![iframe-page-url](https://user-images.githubusercontent.com/44801946/65946397-43fa9600-e460-11e9-93a9-cbc71760ffe9.png)

There is no log in the EPiServerErrors.log file

**Comment by hahuynhniteco** [comment]
@barteksekula For more information, there are multiple sites and multiple language on site instance

**Comment by hahuynhniteco** [comment]
Hi @barteksekula I found the problem in the PageEditPartialRouter.cs, in the RoutePartial function, I comment out these lines:
//segmentContext.ContextMode = ContextMode.Edit;
//segmentContext.RouteData.DataTokens[RoutingConstants.NodeKey] = page.ContentLink;

Then it's working. Could you please help to check? is it necessary to add this code? because it is just review on the preview page?

![image](https://user-images.githubusercontent.com/44801946/66021799-048e8100-e516-11e9-9d54-872d66e9f77b.png)

**Comment by barteksekula** [comment]
@hahuynhniteco yes, those lines are necessary. Without them you won't see the epi-data-property-name attributes rendered and we would not be able to match the pins with right properties.
Does this happen for you in the sample web app from the github repo? or only in your own web app.

**Comment by barteksekula** [comment]
Is the problematic page under the primary site?

**Comment by hahuynhniteco** [comment]
Yes, it does not happen on the sample web app from github but it happened on my primary site. Is there any need to check for the blank page?

**Comment by karorapepper** [comment]
Coincidentally I had similar issue but didn't pursue thinking it just our site specific problem. In my case instead of blank page I get 404 error. I suspect it has something to do permissions to create ExternalContent folder that saves content in edit/draft mode for external reviewers to review.

**Comment by hahuynhniteco** [comment]
Thanks @karorapepper , how can I check the permissions ExternalContent folder on my site?

**Comment by barteksekula** [comment]
@hahuynhniteco just so that we are on the same page, by primary site I mean the one that is marked with PRIMARY option in admin mode, right?

**Comment by hahuynhniteco** [comment]
@barteksekula right, the site is marked with primary in admin mode.

**Comment by barteksekula** [comment]
how many sites and languages do you have? is it the master language?
does the 'view' token work? and it's only 'edit' that does not?
have you tried with any other page?

a lot of questions but I need as much data as possible :)

**Comment by hahuynhniteco** [comment]
Thanks @barteksekula for response. Currently, I have 28 sites on one instance, 5 languages are enabled. The main language is English (Australia) | en-AU
The view working as expected. Just only the edit does not work.
And I have tried lots of page but no luck :)

**Comment by barteksekula** [comment]
Ok thanks. I will try to reproduce this one and get back to you :)

**Comment by barteksekula** [comment]
Fixed in: https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.3.1

**Comment by barteksekula** [comment]
@hahuynhniteco does it work for you now?

**Comment by hahuynhniteco** [comment]
Hi @barteksekula I have upgraded to v0.4.0 but still not work on our site.

**Comment by TNMH** [comment]
Hi @barteksekula 
I also encountered this exact same problem using v0.5.1.

The View functionality works as expected but the Edit functionality results in a blank page. The browser console returns a 'Failed to load resource: the server responded with a status of 404 (Not Found)' error.

**Comment by barteksekula** [comment]
Fixed in https://nuget.episerver.com/package/?id=Advanced.CMS.AdvancedReviews&v=0.5.3
